name: publish-app

on:
  push:
    branches:
      - develop

jobs:
  publish-app:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Deploy to hub
        env:
          AWS_ECR_REPOSITORY_URL: ${{ secrets.AWS_ECR_REPOSITORY_URL}}
        run: |
          cd project1
          export VERSION="$(TZ=UTC git show -s --format=%cd --date=format-local:%Y%m%d-%H%M HEAD).$(git rev-parse --verify HEAD | cut -b 1-10)"
          docker build -t $AWS_ECR_REPOSITORY_URL:${VERSION} .
          docker push $AWS_ECR_REPOSITORY_URL:${VERSION}

          

